server:
  port: 8080
  servlet:
    context-path: /api
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
spring:
  datasource:
    url: jdbc:mysql://localhost/PruebaTecnicaBancoUnion?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: sphs2401
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true
logging:
  level:
    web: debug